FROM php:7.3-apache-stretch

LABEL maintainer="Kevin Padillo <kevin.padillo@decathlon.com>" \
      version="1.0"

RUN apt-get update

RUN apt-get -y install supervisor

COPY --chown=www-data:www-data ./api /srv/app

RUN chown -R www-data:www-data \
      /srv/app/storage \
      /srv/app/bootstrap/cache

COPY ./api/build_config/local/vhost.conf /etc/apache2/sites-available/000-default.conf

WORKDIR /srv/app

# Install dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    libpng-dev \
    libjpeg62-turbo-dev \
    libfreetype6-dev \
    locales \
    zip \
    jpegoptim optipng pngquant gifsicle \
    vim \
    unzip \
    git \
    curl \
    libzip-dev

RUN docker-php-ext-configure gd --with-gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ --with-png-dir=/usr/include/
RUN docker-php-ext-install gd

RUN apt-get update && apt-get install -y \
      libfreetype6-dev \
      libjpeg62-turbo-dev \
      libpng-dev \
      && docker-php-ext-install -j$(nproc) iconv \
      && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
      && docker-php-ext-install -j$(nproc) gd

RUN docker-php-ext-install mbstring pdo pdo_mysql zip \
      && a2enmod rewrite negotiation \
      && a2enmod headers \ 
      && docker-php-ext-install opcache

CMD ["apache2-foreground"]